import { useMemo, useState } from 'react';
import { Activity, ChevronDown, ChevronRight, Clock3, Copy, Download, Folder, Globe, History, Layers3, Plus, RefreshCw, Save, Send, Settings2, Shield, Trash2, X, Zap } from 'lucide-react';
import { RequestModel, ResponseModel, KV } from './types';
import { loadEnv, loadHistory, loadRequests, saveEnv, saveHistory, saveRequests, uid } from './storage';

const kv=():KV=>({key:'',value:'',enabled:true});
const request=():RequestModel=>({id:uid(),name:'New Request',method:'GET',url:'https://jsonplaceholder.typicode.com/posts/1',params:[kv()],headers:[{key:'Accept',value:'application/json',enabled:true},kv()],body:'{\n  "hello": "world"\n}',bodyType:'json',authType:'none',authValue:'',createdAt:Date.now()});
const resolve=(s:string,e:Record<string,string>)=>s.replace(/\{\{([^}]+)\}\}/g,(_,k)=>e[k.trim()]??`{{${k}}}`);

export default function App(){
 const [requests,setRequests]=useState(loadRequests),[history,setHistory]=useState(loadHistory),[env,setEnv]=useState(loadEnv),[active,setActive]=useState<RequestModel>(requests[0]||request());
 const [section,setSection]=useState<'params'|'headers'|'body'|'auth'>('params'),[panel,setPanel]=useState<'request'|'scripts'|'tests'|'docs'|'mock'>('request');
 const [response,setResponse]=useState<ResponseModel|null>(null),[loading,setLoading]=useState(false),[tab,setTab]=useState<'pretty'|'raw'|'headers'>('pretty'),[side,setSide]=useState<'collections'|'history'|'env'>('collections'),[notice,setNotice]=useState('');
 const [preScript,setPreScript]=useState(''),[testScript,setTestScript]=useState("pm.test('Status is successful', () => pm.response.code >= 200 && pm.response.code < 300);");
 const [testResults,setTestResults]=useState<string[]>([]),[form,setForm]=useState<KV[]>([kv()]),[oauth,setOauth]=useState({tokenUrl:'',clientId:'',clientSecret:'',scope:''}),[oauthToken,setOauthToken]=useState('');
 const update=(p:Partial<RequestModel>)=>setActive(x=>({...x,...p}));
 const updateKV=(field:'params'|'headers',i:number,p:Partial<KV>)=>update({[field]:active[field].map((x,j)=>j===i?{...x,...p}:x)} as any);
 const url=useMemo(()=>{const u=resolve(active.url,env);const q=active.params.filter(x=>x.enabled&&x.key).map(x=>encodeURIComponent(resolve(x.key,env))+'='+encodeURIComponent(resolve(x.value,env))).join('&');return q?u+(u.includes('?')?'&':'?')+q:u},[active,env]);
 const flash=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(''),1600)};
 const runTests=(r:ResponseModel)=>{const out:string[]=[];out.push(r.status>=200&&r.status<300?'✓ Status assertion passed':'✕ Status assertion failed');if(testScript.includes('response.code'))out.push(r.status>=200&&r.status<300?'✓ pm.response.code check passed':'✕ pm.response.code check failed');setTestResults(out)};
 const send=async()=>{setLoading(true);setResponse(null);setTestResults([]);try{if(preScript.includes('throw'))throw new Error('Pre-request script threw an error');const headers:Record<string,string>={};active.headers.filter(x=>x.enabled&&x.key).forEach(x=>headers[resolve(x.key,env)]=resolve(x.value,env));if(active.authType==='bearer'&&active.authValue)headers.Authorization='Bearer '+resolve(active.authValue,env);if(active.authType==='basic'&&active.authValue)headers.Authorization='Basic '+btoa(resolve(active.authValue,env));if(active.authType==='apikey'&&active.authValue)headers['X-API-Key']=resolve(active.authValue,env);if(active.authType==='oauth2'&&oauthToken)headers.Authorization='Bearer '+oauthToken;
 let body:string|undefined=active.bodyType==='none'?undefined:resolve(active.body,env);if(active.bodyType==='json'&&!headers['Content-Type'])headers['Content-Type']='application/json';
 if(active.bodyType!=='none'&&active.method==='GET') body=undefined;
 const r=await fetch('/proxy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,method:active.method,headers,body})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Proxy request failed');setResponse(d);runTests(d);const h=[active,...history.filter(x=>x.url!==active.url||x.method!==active.method)];setHistory(h);saveHistory(h)}catch(e){const d={status:0,statusText:'Request Error',headers:{},body:String((e as Error).message||e),time:0};setResponse(d);setTestResults(['✕ '+d.body])}finally{setLoading(false)}};
 const save=()=>{const all=[...requests.filter(x=>x.id!==active.id),active];setRequests(all);saveRequests(all);flash('Saved')};
 const create=()=>setActive(request());
 const importOpenAPI=async(f:File)=>{try{const spec=JSON.parse(await f.text());const base=spec.servers?.[0]?.url||spec.basePath||'';const made:RequestModel[]=[];Object.entries(spec.paths||{}).forEach(([path,item]:any)=>Object.entries(item||{}).forEach(([method,op]:any)=>{if(!/^(get|post|put|patch|delete|head|options)$/i.test(method))return;made.push({...request(),id:uid(),name:op?.summary||op?.operationId||method.toUpperCase()+' '+path,method:method.toUpperCase(),url:base+path,createdAt:Date.now()})}));if(!made.length)throw new Error('No HTTP operations found');const all=[...requests,...made];setRequests(all);saveRequests(all);setActive(made[0]);flash('Imported '+made.length+' endpoints')}catch(e){flash((e as Error).message||'OpenAPI JSON import failed')}};
 const getOAuth=async()=>{try{const r=await fetch('/oauth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(oauth)});const d=await r.json();if(!r.ok)throw new Error(d.error||d.body);const x=JSON.parse(d.body);setOauthToken(x.access_token||'');flash('OAuth token received')}catch(e){flash('OAuth: '+String((e as Error).message))}};
 const copy=()=>{navigator.clipboard.writeText(response?.body||'');flash('Copied')};
 const curl=()=>{let c=`curl -X ${active.method} '${url}'`;active.headers.filter(x=>x.enabled&&x.key).forEach(x=>c+=` -H '${x.key}: ${x.value}'`);if(active.bodyType!=='none')c+=` --data-raw '${active.body.replace(/'/g,"'\\''")}'`;navigator.clipboard.writeText(c);flash('cURL copied')};
 const exportReq=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(active,null,2)],{type:'application/json'}));a.download=(active.name||'request')+'.json';a.click()};
 const addCollection=()=>{const n=prompt('Collection name');if(n)flash('Collection "'+n+'" created')};
 return <div className="app"><header className="topbar"><div className="brand"><div className="brandmark"><Zap size={18}/></div><span>Postman <b>Pro</b></span></div><div className="workspace"><Layers3 size={15}/> My Workspace <ChevronDown size={14}/></div><div className="top-actions"><button onClick={()=>flash('Local workspace synced')}><RefreshCw size={15}/> Sync</button><button><Settings2 size={15}/></button><div className="avatar">N</div></div></header>
 <div className="layout"><aside className="sidebar"><div className="side-tabs"><button className={side==='collections'?'active':''} onClick={()=>setSide('collections')}><Folder size={16}/>Collections</button><button className={side==='history'?'active':''} onClick={()=>setSide('history')}><History size={16}/>History</button><button className={side==='env'?'active':''} onClick={()=>setSide('env')}><Globe size={16}/>Environment</button></div>
 {side==='collections'&&<div className="side-content"><div className="side-heading"><span>Collections</span><button onClick={addCollection}><Plus size={16}/></button></div><div className="tree-row"><ChevronDown size={13}/><Folder size={15}/>My API Collection</div>{requests.map(r=><button className={'request-row '+(r.id===active.id?'selected':'')} key={r.id} onClick={()=>{setActive(r);setPanel('request')}}><span className={'method-dot '+r.method.toLowerCase()}>{r.method}</span><span>{r.name}</span></button>)}{!requests.length&&<div className="empty-side">No saved requests yet.</div>}</div>}
 {side==='history'&&<div className="side-content"><div className="side-heading"><span>Recent requests</span></div>{history.map((r,i)=><button className="request-row" key={r.id+i} onClick={()=>setActive({...r,id:uid()})}><span className={'method-dot '+r.method.toLowerCase()}>{r.method}</span><span>{r.name}</span></button>)}</div>}
 {side==='env'&&<div className="side-content"><div className="side-heading"><span>Local environment</span><button onClick={()=>{const k=prompt('Variable');if(k){const n={...env,[k]:prompt('Value')||''};setEnv(n);saveEnv(n)}}}><Plus size={16}/></button></div>{Object.entries(env).map(([k,v])=><div className="env-row" key={k}><code>{'{{'+k+'}}'}</code><input value={v} onChange={e=>{const n={...env,[k]:e.target.value};setEnv(n);saveEnv(n)}}/></div>)}</div>}
 <div className="side-bottom"><button><Shield size={15}/>Security</button><button><Activity size={15}/>Console</button></div></aside>
 <main className="main"><div className="tabsbar"><div className="req-tab active"><span className="tab-method">{active.method}</span>{active.name}<X size={13}/></div><button className="new-tab" onClick={create}><Plus size={16}/></button></div>
 <div className="request-pane"><div className="crumb">My API Collection <ChevronRight size={13}/><span className="muted">{active.name}</span></div><div className="request-title"><input value={active.name} onChange={e=>update({name:e.target.value})}/><div className="title-actions"><button onClick={exportReq}><Download size={15}/>Export</button><button onClick={curl}><Copy size={15}/>cURL</button><button className="primary" onClick={save}><Save size={15}/>{notice||'Save'}</button></div></div>
 <div className="urlbar"><select value={active.method} onChange={e=>update({method:e.target.value})}>{['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'].map(m=><option key={m}>{m}</option>)}</select><input value={active.url} onChange={e=>update({url:e.target.value})}/><button className="send" onClick={send} disabled={loading}>{loading?<RefreshCw className="spin" size={17}/>:<Send size={17}/>} {loading?'Sending':'Send'}</button></div>
 <div className="pro-toolbar">{(['request','scripts','tests','docs','mock'] as const).map(p=><button key={p} className={panel===p?'active':''} onClick={()=>setPanel(p)}>{p[0].toUpperCase()+p.slice(1)}</button>)}<label className="import-openapi"><Download size={13}/>Import OpenAPI<input type="file" accept=".json" onChange={e=>{const f=e.target.files?.[0];if(f)importOpenAPI(f)}}/></label></div>
 {panel==='request'&&<><div className="editor-tabs">{(['params','headers','body','auth'] as const).map(s=><button className={section===s?'active':''} onClick={()=>setSection(s)} key={s}>{s==='headers'?'Headers ('+active.headers.filter(x=>x.enabled&&x.key).length+')':s==='auth'?'Authorization':s[0].toUpperCase()+s.slice(1)}</button>)}</div>{section==='params'&&<KVEditor title="Query Parameters" rows={active.params} onChange={(i,p)=>updateKV('params',i,p)} onAdd={()=>update({params:[...active.params,kv()]})}/>} {section==='headers'&&<KVEditor title="Request Headers" rows={active.headers} onChange={(i,p)=>updateKV('headers',i,p)} onAdd={()=>update({headers:[...active.headers,kv()]})}/>} {section==='body'&&<div className="body-editor"><div className="body-toolbar"><select value={active.bodyType} onChange={e=>update({bodyType:e.target.value as any})}><option value="none">none</option><option value="json">JSON</option><option value="text">Text</option></select></div><textarea className="codearea" value={active.body} disabled={active.bodyType==='none'} onChange={e=>update({body:e.target.value})}/></div>} {section==='auth'&&<Auth active={active} update={update} oauth={oauth} setOauth={setOauth} getOAuth={getOAuth} token={oauthToken}/>}</>}
 {panel==='scripts'&&<div className="advanced-panel"><h3>Pre-request Script</h3><textarea className="codearea" value={preScript} onChange={e=>setPreScript(e.target.value)} placeholder="// Set variables before sending"/><h3>Post-response Script</h3><textarea className="codearea" placeholder="// Extract or transform response data"/></div>}
 {panel==='tests'&&<div className="advanced-panel"><h3>Tests & Assertions</h3><textarea className="codearea" value={testScript} onChange={e=>setTestScript(e.target.value)}/>{testResults.map((x,i)=><div className="test-result" key={i}>{x}</div>)}</div>}
 {panel==='docs'&&<div className="advanced-panel"><h3>API Documentation</h3><p>Generate Markdown documentation from this endpoint.</p><button className="primary" onClick={()=>{navigator.clipboard.writeText(`# ${active.name}\n\n**${active.method}** ${url}\n\n## Request\n\n${active.bodyType==='none'?'No body':active.body}`);flash('Markdown copied')}}>Copy Markdown</button></div>}
 {panel==='mock'&&<div className="advanced-panel"><h3>Mock Server</h3><p>Use the built-in mock endpoint to return a saved response.</p><div className="mock-url"><code>/mock</code><button onClick={async()=>{const r=await fetch('/mock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:response?.status||200,headers:response?.headers||{'Content-Type':'application/json'},body:response?.body||'{}'})});flash('Mock response created: '+r.status)}}>Create Mock</button></div></div>}
 </div><div className="response-pane"><div className="response-head"><div><b>Response</b>{response&&<span className={'status '+(response.status>=200&&response.status<300?'ok':'bad')}>{response.status||'ERR'} {response.statusText}</span>}</div>{response&&<div className="response-meta"><span><Clock3 size={13}/>{response.time} ms</span><span>{new Blob([response.body]).size} B</span><button onClick={copy}><Copy size={14}/></button></div>}</div>{!response?<div className="response-empty"><div className="empty-icon"><Send size={25}/></div><h3>Ready when you are</h3><p>Send a request to inspect the response.</p></div>:<div className="response-content"><div className="response-tabs">{(['pretty','raw','headers'] as const).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t==='headers'?'Headers ('+Object.keys(response.headers).length+')':t[0].toUpperCase()+t.slice(1)}</button>)}</div>{tab==='headers'?<div className="response-headers">{Object.entries(response.headers).map(([k,v])=><div key={k}><b>{k}</b><span>{v}</span></div>)}</div>:<pre className="response-code">{tab==='pretty'?pretty(response.body):response.body}</pre>}</div>}</div></main></div></div>;
}
function pretty(s:string){try{return JSON.stringify(JSON.parse(s),null,2)}catch{return s}}
function KVEditor({title,rows,onChange,onAdd}:{title:string;rows:KV[];onChange:(i:number,p:Partial<KV>)=>void;onAdd:()=>void}){return <div className="kv-editor"><div className="kv-head"><span>{title}</span><span>Value</span><span>Enabled</span><span/></div>{rows.map((r,i)=><div className="kv-row" key={i}><input className="check" type="checkbox" checked={r.enabled} onChange={e=>onChange(i,{enabled:e.target.checked})}/><input placeholder="key" value={r.key} onChange={e=>onChange(i,{key:e.target.value})}/><input placeholder="value" value={r.value} onChange={e=>onChange(i,{value:e.target.value})}/><button onClick={()=>onChange(i,{key:'',value:'',enabled:false})}><Trash2 size={14}/></button></div>)}<button className="add-row" onClick={onAdd}><Plus size={14}/>Add row</button></div>}
function Auth({active,update,oauth,setOauth,getOAuth,token}:{active:RequestModel;update:(p:Partial<RequestModel>)=>void;oauth:any;setOauth:any;getOAuth:()=>void;token:string}){return <div className="auth-panel"><div><label>Type</label><select value={active.authType} onChange={e=>update({authType:e.target.value as any})}><option value="none">No Auth</option><option value="bearer">Bearer Token</option><option value="basic">Basic Auth</option><option value="apikey">API Key</option><option value="oauth2">OAuth 2.0</option></select></div>{active.authType!=='none'&&active.authType!=='oauth2'&&<div className="auth-value"><label>Credential</label><input type={active.authType==='bearer'?'password':'text'} value={active.authValue} onChange={e=>update({authValue:e.target.value})}/></div>}{active.authType==='oauth2'&&<div className="oauth-box"><input placeholder="Token URL" value={oauth.tokenUrl} onChange={e=>setOauth({...oauth,tokenUrl:e.target.value})}/><input placeholder="Client ID" value={oauth.clientId} onChange={e=>setOauth({...oauth,clientId:e.target.value})}/><input placeholder="Client Secret" type="password" value={oauth.clientSecret} onChange={e=>setOauth({...oauth,clientSecret:e.target.value})}/><input placeholder="Scope" value={oauth.scope} onChange={e=>setOauth({...oauth,scope:e.target.value})}/><button className="primary" onClick={getOAuth}>Get Token</button>{token&&<input value={token} readOnly/>}</div>}</div>}
