import {useState} from 'react';
import {Play,CheckCircle2,XCircle,Clock3,BarChart3,Monitor,Server,ShieldCheck,Plus,RefreshCw} from 'lucide-react';
import {loadRequests} from './storage';

type Result={name:string;method:string;status:number;ok:boolean;time:number};
export default function AutomationCenter(){const [tab,setTab]=useState<'runner'|'monitors'|'mocks'|'reports'>('runner');const [runs,setRuns]=useState<Result[]>([]);const [running,setRunning]=useState(false);const requests=loadRequests();
 const run=async()=>{setRunning(true);setRuns([]);for(const r of requests){const t=performance.now();try{const res=await fetch('/proxy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:r.url,method:r.method,headers:Object.fromEntries(r.headers.filter(x=>x.enabled&&x.key).map(x=>[x.key,x.value])),body:r.bodyType==='none'?undefined:r.body})});setRuns(x=>[...x,{name:r.name,method:r.method,status:res.status,ok:res.ok,time:Math.round(performance.now()-t)}])}catch{setRuns(x=>[...x,{name:r.name,method:r.method,status:0,ok:false,time:Math.round(performance.now()-t)}])}}setRunning(false)};
 const success=runs.filter(x=>x.ok).length;return <div className="automation"><header><div><span className="eyebrow">POSTMAN PRO AUTOMATION</span><h1>API Automation Center</h1><p>Run collections, monitor APIs, inspect test results and manage delivery workflows.</p></div><button className="auto-primary" onClick={run} disabled={running||!requests.length}><Play size={15}/>{running?'Running collection…':'Run collection'}</button></header><nav className="auto-tabs">{[['runner','Collection Runner',Play],['monitors','Monitors',Monitor],['mocks','Mock Servers',Server],['reports','Reports',BarChart3]].map(([id,label,I]:any)=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I size={15}/>{label}</button>)}</nav>{tab==='runner'&&<><section className="auto-stats"><div><b>{requests.length}</b><span>Requests available</span></div><div><b>{runs.length}</b><span>Executed</span></div><div><b>{success}</b><span>Passed</span></div><div><b>{runs.length?Math.round(success/runs.length*100):0}%</b><span>Pass rate</span></div></section><section className="run-table"><div className="run-head"><span>Request</span><span>Method</span><span>Status</span><span>Time</span><span>Result</span></div>{runs.length?runs.map((r,i)=><div className="run-row" key={i}><span>{r.name}</span><code>{r.method}</code><span>{r.status||'ERR'}</span><span>{r.time} ms</span>{r.ok?<CheckCircle2 className="pass" size={16}/>:<XCircle className="fail" size={16}/>}</div>):<div className="run-empty"><ShieldCheck size={28}/><h3>Collection Runner</h3><p>Run your imported or saved requests as a collection and get a step-by-step report.</p></div>}</section></>}{tab==='monitors'&&<Placeholder icon={Monitor} title="API Monitors" text="Schedule health checks and track availability, latency and failures." action="Create monitor"/>}{tab==='mocks'&&<Placeholder icon={Server} title="Mock Servers" text="Create mock endpoints from your collections while backend services are still being built." action="Create mock server"/>}{tab==='reports'&&<Placeholder icon={BarChart3} title="Run Reports" text="Turn collection runs into pass-rate, latency and failure reports." action="Generate report"/>}</div>}
function Placeholder({icon:Icon,title,text,action}:{icon:any;title:string;text:string;action:string}){return <section className="auto-placeholder"><Icon size={30}/><h2>{title}</h2><p>{text}</p><button><Plus size={14}/>{action}</button></section>}
