import React,{useEffect,useRef,useState} from 'react';
import {Download,Upload,X,CheckCircle2,AlertCircle} from 'lucide-react';
import yaml from 'js-yaml';
import {RequestModel} from './types';
import {loadRequests,saveRequests,uid} from './storage';
const blank=(name:string,method:string,url:string):RequestModel=>({id:uid(),name,method,url,params:[],headers:[{key:'Accept',value:'application/json',enabled:true}],body:'',bodyType:'none',authType:'none',authValue:'',createdAt:Date.now()});
function openapi(s:any){const a:RequestModel[]=[];const base=s?.servers?.[0]?.url||s?.basePath||'';Object.entries<any>(s?.paths||{}).forEach(([path,item])=>Object.entries<any>(item||{}).forEach(([method,op])=>{if(!/^(get|post|put|patch|delete|head|options)$/i.test(method))return;a.push({...blank(op?.summary||op?.operationId||method.toUpperCase()+' '+path,method.toUpperCase(),base+path),params:(op?.parameters||[]).filter((p:any)=>p.in==='query'||p.in==='path').map((p:any)=>({key:p.name||'',value:p.example??p.default??'',enabled:true})),body:op?.requestBody?'{}':'',bodyType:op?.requestBody?'json':'none'})}));return a}
function postman(s:any){const a:RequestModel[]=[];const walk=(xs:any[])=>xs?.forEach(x=>{if(x.item)walk(x.item);if(x.request){const r=x.request,u=typeof r.url==='string'?r.url:r.url?.raw||'';a.push({...blank(x.name||r.name||'Imported request',(r.method||'GET').toUpperCase(),u),headers:(r.header||[]).map((h:any)=>({key:h.key||'',value:h.value||'',enabled:h.disabled!==true})),body:r.body?.raw||'',bodyType:r.body?.raw?'json':'none'})}});walk(s?.item||[]);return a}
function curl(t:string){return t.split(/\n+/).flatMap(line=>{if(!/\bcurl\b/i.test(line))return [];const u=line.match(/['\"](https?:\/\/[^'\"]+)['\"]/i);if(!u)return [];const m=line.match(/-X\s+([A-Z]+)/i);const r=blank((m?.[1]||'GET')+' '+u[1],(m?.[1]||'GET'),u[1]);const hs=[...line.matchAll(/(?:-H|--header)\s+['\"]([^'\"]+)['\"]/gi)].map(x=>{const i=x[1].indexOf(':');return {key:i>0?x[1].slice(0,i):x[1],value:i>0?x[1].slice(i+1).trim():'',enabled:true}});r.headers=hs.length?hs:r.headers;const d=line.match(/(?:--data-raw|--data|-d)\s+['\"]([\s\S]*?)['\"]/i);if(d){r.body=d[1];r.bodyType='json'}return [r]})}
function parse(t:string){let s:any;try{s=JSON.parse(t)}catch{try{s=yaml.load(t)}catch{const c=curl(t);if(c.length)return c;throw new Error('Could not parse this import.')}}if(s?.openapi||s?.swagger)return openapi(s);if(s?.info?.schema&&s?.item)return postman(s);if(s?.item)return postman(s);const c=curl(t);if(c.length)return c;throw new Error('Unsupported import. Use OpenAPI JSON/YAML, Postman Collection v2 JSON, or cURL.')}
export default function ImportCenter({close}:{close:()=>void}){const [text,setText]=useState(''),[name,setName]=useState(''),[msg,setMsg]=useState(''),[ok,setOk]=useState(false),input=useRef<HTMLInputElement>(null);useEffect(()=>{const f=(e:KeyboardEvent)=>e.key==='Escape'&&close();addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[]);const importNow=()=>{try{const made=parse(text);if(!made.length)throw new Error('No endpoints found');saveRequests([...loadRequests(),...made]);setOk(true);setMsg(`Imported ${made.length} requests. Refreshing UI…`);setTimeout(()=>location.reload(),500)}catch(e){setOk(false);setMsg((e as Error).message)}};return <div className="import-overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="import-modal"><div className="import-modal-head"><div><small>POSTMAN PRO IMPORT CENTER</small><h2>Import APIs & collections</h2><p>Bring OpenAPI definitions, Postman Collection v2 files, or cURL into the active workspace.</p></div><button onClick={close}><X size={18}/></button></div><div className="import-drop" onClick={()=>input.current?.click()}><input ref={input} hidden type="file" accept=".json,.yaml,.yml,.txt,.curl" onChange={async e=>{const f=e.target.files?.[0];if(f){setName(f.name);setText(await f.text())}}}/><Upload size={22}/><b>{name||'Choose import file'}</b><span>OpenAPI JSON/YAML · Postman Collection v2 · cURL</span></div><div className="import-or">OR PASTE</div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste JSON/YAML collection, OpenAPI definition, or cURL…"/>{msg&&<div className={'import-message '+(ok?'success':'error')}>{ok?<CheckCircle2 size={15}/>:<AlertCircle size={15}/>} {msg}</div>}<div className="import-actions"><button onClick={close}>Cancel</button><button className="import-primary" disabled={!text.trim()} onClick={importNow}><Download size={15}/>Import into workspace</button></div></div></div>}
