import {useMemo,useState} from 'react';
import {CheckCircle2,Code2,Download,FileJson,Play,Radio,RefreshCw,ShieldCheck,Upload,Wifi,X} from 'lucide-react';
import {loadCollections,loadRequests,saveCollections,saveRequests,uid} from './storage';
import {Collection,RequestModel} from './types';

type ImportKind='openapi'|'raml'|'graphql'|'curl'|'wsdl'|'har';
const endpoint:Record<ImportKind,string>={openapi:'/api/platform/openapi/import',raml:'/api/platform/raml/import',graphql:'/api/platform/graphql/import',curl:'/api/platform/curl/import',wsdl:'/api/platform/wsdl/import',har:'/api/platform/har/import'};
const toPostman=(c:Collection,rs:RequestModel[])=>({info:{_postman_id:c.id,name:c.name,schema:'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'},item:rs.filter(r=>r.collectionId===c.id).map(r=>({name:r.name,request:{method:r.method,header:r.headers.filter(h=>h.enabled&&h.key).map(h=>({key:h.key,value:h.value})),url:{raw:r.url},body:r.bodyType==='none'?undefined:{mode:'raw',raw:r.body||''}}}))});
const flatten=(c:any):RequestModel[]=>{const out:RequestModel[]=[];const walk=(items:any[],folders:string[]=[])=>(items||[]).forEach((i:any)=>{if(i.request){const u=typeof i.request.url==='string'?i.request.url:i.request.url?.raw||'';out.push({id:uid(),name:i.name||'Request',method:String(i.request.method||'GET').toUpperCase(),url:u,params:[],headers:(i.request.header||[]).map((h:any)=>({key:String(h.key||''),value:String(h.value??''),enabled:h.disabled!==true})),body:i.request.body?.raw||'',bodyType:i.request.body?'text':'none',authType:'none',authValue:'',createdAt:Date.now(),folderPath:folders});}else if(Array.isArray(i.item))walk(i.item,[...folders,String(i.name||'Folder')])});walk(c?.item||[]);return out};

export default function PlatformProCenter(){
 const [tab,setTab]=useState<'import'|'codegen'|'runner'|'validate'|'realtime'|'export'>('import');
 const [kind,setKind]=useState<ImportKind>('openapi'),[input,setInput]=useState(''),[result,setResult]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [language,setLanguage]=useState('javascript'),[variant,setVariant]=useState('fetch'),[selected,setSelected]=useState(''),[env,setEnv]=useState('{}'),[iterations,setIterations]=useState(1);
 const [mode,setMode]=useState<'ws'|'sse'>('ws'),[realtimeUrl,setRealtimeUrl]=useState('wss://echo.websocket.events'),[realtimeMessage,setRealtimeMessage]=useState('Hello from Postman Pro'),[log,setLog]=useState<string[]>([]);const [socket,setSocket]=useState<WebSocket|null>(null);const [source,setSource]=useState<EventSource|null>(null);
 const requests=loadRequests(),collections=loadCollections();const request=requests.find(r=>r.id===selected)||requests[0];const collection=useMemo(()=>collections.find(c=>c.id===request?.collectionId)||collections[0],[collections,request]);
 const flash=(s:string)=>{setMessage(s);setTimeout(()=>setMessage(''),3500)};
 const doImport=async()=>{if(!input.trim())return;setBusy(true);try{const body=kind==='curl'?{curl:input}:kind==='har'?{har:JSON.parse(input)}:{spec:input};const r=await fetch(endpoint[kind],{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Import failed');const c=d.collection;const imported=flatten(c);const id=uid();const mapped=imported.map(x=>({...x,id:uid(),collectionId:id}));const nc:Collection={id,name:c.info?.name||c.name||`${kind.toUpperCase()} Import`,requestIds:mapped.map(x=>x.id),createdAt:Date.now()};saveCollections([...collections,nc]);saveRequests([...requests,...mapped]);setResult(JSON.stringify(c,null,2));flash(`Imported ${mapped.length} requests into ${nc.name}`);}catch(e){flash(String((e as Error).message||e))}finally{setBusy(false)}};
 const generate=async()=>{if(!request)return;setBusy(true);try{const r=await fetch('/api/platform/codegen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request,language,variant})});const d=await r.json();if(!r.ok)throw new Error(d.error);setResult(d.code||'');flash('Code generated');}catch(e){flash(String((e as Error).message||e))}finally{setBusy(false)}};
 const run=async()=>{if(!collection)return;setBusy(true);try{const r=await fetch('/api/platform/runner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({collection:toPostman(collection,requests),environment:JSON.parse(env||'{}'),iterationCount:iterations})});const d=await r.json();if(!r.ok)throw new Error(d.error);setResult(JSON.stringify(d,null,2));flash('Collection run completed');}catch(e){flash(String((e as Error).message||e))}finally{setBusy(false)}};
 const validate=async()=>{if(!collection)return;setBusy(true);try{const r=await fetch('/api/platform/collection/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({collection:toPostman(collection,requests)})});const d=await r.json();if(!r.ok)throw new Error(d.error);setResult(JSON.stringify(d,null,2));flash(d.valid?'Collection is valid':'Collection has validation issues');}catch(e){flash(String((e as Error).message||e))}finally{setBusy(false)}};
 const exportIt=async(kind:'collection'|'har')=>{if(!collection)return;setBusy(true);try{const r=await fetch(kind==='collection'?'/api/platform/collection/export':'/api/platform/har/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({collection:toPostman(collection,requests)})});const d=await r.json();if(!r.ok)throw new Error(d.error);const text=JSON.stringify(d,null,2);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=kind==='collection'?`${collection.name}.postman_collection.json`:`${collection.name}.har`;a.click();URL.revokeObjectURL(a.href);flash('Export completed');}catch(e){flash(String((e as Error).message||e))}finally{setBusy(false)}};
 const connect=()=>{setLog([]);if(mode==='ws'){const ws=new WebSocket(realtimeUrl);ws.onopen=()=>setLog(x=>[...x,'CONNECTED']);ws.onmessage=e=>setLog(x=>[...x,'← '+e.data]);ws.onerror=()=>setLog(x=>[...x,'ERROR']);ws.onclose=()=>setLog(x=>[...x,'CLOSED']);setSocket(ws);}else{const es=new EventSource(realtimeUrl);es.onopen=()=>setLog(x=>[...x,'CONNECTED']);es.onmessage=e=>setLog(x=>[...x,'← '+e.data]);es.onerror=()=>setLog(x=>[...x,'ERROR / CLOSED']);setSource(es)}};
 const disconnect=()=>{socket?.close();source?.close();setSocket(null);setSource(null);setLog(x=>[...x,'STOPPED'])};
 const send=()=>{if(socket?.readyState===WebSocket.OPEN){socket.send(realtimeMessage);setLog(x=>[...x,'→ '+realtimeMessage])}else flash('WebSocket is not connected')};
 const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([result],{type:'text/plain'}));a.download='postman-pro-output.txt';a.click();URL.revokeObjectURL(a.href)};
 const types:[ImportKind,string,string][]=[['openapi','OpenAPI / Swagger','OAS 3.x · Swagger 2'],['raml','RAML','RAML 1.0'],['graphql','GraphQL','Schema / SDL'],['curl','cURL','Command → request'],['wsdl','WSDL','SOAP services'],['har','HAR','HTTP Archive']];
 return <section className="platform-center"><header className="platform-head"><div><div className="eyebrow">POSTMAN PRO PLATFORM ENGINE</div><h2>Complete API lifecycle workspace</h2><p>Design, import, execute, test, generate, export and connect to realtime APIs.</p></div><ShieldCheck size={24}/></header><div className="platform-badges"><span><CheckCircle2 size={13}/>Collection v2.1</span><span><CheckCircle2 size={13}/>OpenAPI 3.0 / 3.1 / Swagger 2</span><span><CheckCircle2 size={13}/>Newman runtime</span><span><CheckCircle2 size={13}/>Code generators</span><span><CheckCircle2 size={13}/>WebSocket + SSE</span></div><nav className="platform-tabs">{[['import','Import',Upload],['codegen','Code Generator',Code2],['runner','Collection Runner',Play],['validate','Validate',ShieldCheck],['realtime','Realtime',Radio],['export','Export',Download]].map(([id,label,Icon]:any)=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={15}/>{label}</button>)}</nav>{message&&<div className="platform-message">{message}</div>}
 {tab==='import'&&<div className="platform-card"><div className="platform-card-head"><div><b>Universal API importer</b><span>Convert API descriptions and captured traffic into a workspace collection.</span></div><button className="platform-primary" onClick={doImport} disabled={!input.trim()||busy}><Upload size={14}/>{busy?'Importing…':'Import'}</button></div><div className="platform-import-grid">{types.map(([id,label,sub])=><button key={id} className={'import-type '+(kind===id?'active':'')} onClick={()=>setKind(id)}><FileJson size={17}/><b>{label}</b><small>{sub}</small></button>)}</div><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={kind==='curl'?'Paste cURL commands…':kind==='har'?'Paste HAR JSON…':`Paste ${kind.toUpperCase()} specification…`}/><pre>{result||'Converted collection preview will appear here.'}</pre></div>}
 {tab==='codegen'&&<div className="platform-grid"><div className="platform-card"><div className="platform-card-head"><b>Generate client code</b><button className="platform-primary" onClick={generate} disabled={!request||busy}><Code2 size={14}/>Generate</button></div><label>Request<select value={selected} onChange={e=>setSelected(e.target.value)}>{requests.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><div className="platform-form-grid"><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="javascript">JavaScript</option><option value="nodejs">NodeJs</option><option value="python">Python</option><option value="java">Java</option><option value="go">Go</option><option value="csharp">C#</option><option value="php">PHP</option><option value="ruby">Ruby</option><option value="kotlin">Kotlin</option><option value="swift">Swift</option><option value="rust">Rust</option><option value="curl">cURL</option><option value="powershell">PowerShell</option></select></label><label>Variant<input value={variant} onChange={e=>setVariant(e.target.value)} placeholder="fetch / requests / okhttp"/></label></div></div><div className="platform-card"><div className="platform-card-head"><b>Generated code</b><button onClick={download} disabled={!result}><Download size={14}/>Export</button></div><pre>{result||'Select a request and generate code.'}</pre></div></div>}
 {tab==='runner'&&<div className="platform-card"><div className="platform-card-head"><div><b>Collection Runner</b><span>Run collections with environments and iterations.</span></div><button className="platform-primary" onClick={run} disabled={!collection||busy}><Play size={14}/>{busy?'Running…':'Run collection'}</button></div><div className="platform-form-grid"><label>Collection<select value={collection?.id||''} onChange={e=>{const r=requests.find(x=>x.collectionId===e.target.value);setSelected(r?.id||'')}}>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Iterations<input type="number" min="1" value={iterations} onChange={e=>setIterations(Math.max(1,Number(e.target.value)))}/></label></div><label>Environment JSON<textarea value={env} onChange={e=>setEnv(e.target.value)}/></label><pre>{result||'Runner report will appear here.'}</pre></div>}
 {tab==='validate'&&<div className="platform-card"><div className="platform-card-head"><div><b>Collection validation</b><span>Validate before export or CI.</span></div><button className="platform-primary" onClick={validate} disabled={!collection||busy}><RefreshCw size={14}/>Validate</button></div><div className="platform-info"><FileJson size={18}/><div><b>{collection?.name||'No collection selected'}</b><p>{collection?`${requests.filter(r=>r.collectionId===collection.id).length} requests ready.`:'Create or import a collection first.'}</p></div></div><pre>{result||'Validation report will appear here.'}</pre></div>}
 {tab==='realtime'&&<div className="platform-card"><div className="platform-card-head"><div><b>Realtime API client</b><span>WebSocket and Server-Sent Events.</span></div><Wifi size={20}/></div><div className="platform-form-grid"><label>Protocol<select value={mode} onChange={e=>setMode(e.target.value as 'ws'|'sse')}><option value="ws">WebSocket</option><option value="sse">Server-Sent Events</option></select></label><label>URL<input value={realtimeUrl} onChange={e=>setRealtimeUrl(e.target.value)}/></label></div><div className="realtime-actions"><button className="platform-primary" onClick={connect}><Radio size={14}/>Connect</button><button onClick={disconnect}><X size={14}/>Disconnect</button><button onClick={send} disabled={mode!=='ws'||!socket}>Send</button></div><label>Message<textarea value={realtimeMessage} onChange={e=>setRealtimeMessage(e.target.value)}/></label><pre>{log.length?log.join('\n'):'Realtime events will appear here.'}</pre></div>}
 {tab==='export'&&<div className="platform-card"><div className="platform-card-head"><div><b>Export & interoperability</b><span>Portable collection and traffic formats for CI and other API tools.</span></div></div><div className="export-grid"><button onClick={()=>exportIt('collection')} disabled={!collection||busy}><Download size={18}/><b>Postman Collection v2.1</b><small>Standard collection JSON</small></button><button onClick={()=>exportIt('har')} disabled={!collection||busy}><Download size={18}/><b>HAR</b><small>HTTP Archive</small></button></div></div>}
 </section>;
}
