import {useEffect,useState} from 'react';
import {Activity,Bot,Plus,Play,RefreshCw} from 'lucide-react';
export default function ProductOpsCenter(){
 const [tab,setTab]=useState<'monitor'|'assistant'>('monitor'); const [monitors,setMonitors]=useState<any[]>([]); const [name,setName]=useState('Production API'); const [url,setUrl]=useState('https://httpbin.org/status/200'); const [prompt,setPrompt]=useState('Generate tests for this API'); const [answer,setAnswer]=useState(''); const [output,setOutput]=useState(''); const [busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch('/api/product/monitors');const d=await r.json();setMonitors(d.monitors||[])}; useEffect(()=>{load()},[]);
 const create=async()=>{setBusy(true);try{await fetch('/api/product/monitors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,url,method:'GET'})});await load()}finally{setBusy(false)}};
 const run=async(id:string)=>{setBusy(true);try{const r=await fetch(`/api/product/monitors/${id}/run`,{method:'POST'});setOutput(JSON.stringify(await r.json(),null,2));await load()}finally{setBusy(false)}};
 const ask=async()=>{setBusy(true);try{const r=await fetch('/api/product/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});const d=await r.json();setAnswer(d.answer||'')}finally{setBusy(false)}};
 return <section className="platform-center"><header className="platform-head"><div><div className="eyebrow">POSTMAN PRO OPERATIONS</div><h2>Monitor & AI Assistant</h2><p>Continuously check APIs and get actionable API-development guidance.</p></div><Activity size={24}/></header><nav className="platform-tabs"><button className={tab==='monitor'?'active':''} onClick={()=>setTab('monitor')}><Activity size={15}/>Monitors</button><button className={tab==='assistant'?'active':''} onClick={()=>setTab('assistant')}><Bot size={15}/>API Assistant</button></nav>{tab==='monitor'?<div className="platform-grid"><div className="platform-card"><div className="platform-card-head"><b>Create monitor</b><button className="platform-primary" onClick={create} disabled={busy}><Plus size={14}/>Add monitor</button></div><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>URL<input value={url} onChange={e=>setUrl(e.target.value)}/></label></div><div className="platform-card"><div className="platform-card-head"><b>Monitors</b><button onClick={load}><RefreshCw size={14}/></button></div>{monitors.length?monitors.map(m=><div className="monitor-row" key={m.id}><div><b>{m.name}</b><small>{m.method} · {m.url}</small><span>{m.lastRun?`${m.lastRun.status} · ${m.lastRun.time}ms`:'Not run'}</span></div><button onClick={()=>run(m.id)} disabled={busy}><Play size={14}/>Run</button></div>):<p className="muted">No monitors yet.</p>}<pre>{output||'Monitor result will appear here.'}</pre></div></div>:<div className="platform-card"><div className="platform-card-head"><b><Bot size={18}/> Ask the API Assistant</b><button className="platform-primary" onClick={ask} disabled={busy}>{busy?'Thinking…':'Ask'}</button></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="How should I test this endpoint?"/><div className="answer">{answer||'Ask for tests, authentication, performance, debugging, OpenAPI, GraphQL, WebSocket or automation guidance.'}</div></div>}</section>;
}
